version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5436:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  qdrant:
    image: qdrant/qdrant
    ports:
      - "63334:6333"

  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - qdrant
